import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ClientProvider, EntertainmentConfig } from "@repo/ui";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

EntertainmentConfig.initialize({
  environment: "development",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Here we need to set the config on the server side
  // const config = EntertainmentConfig.getConfig();

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
